Repository natron-io/tenant-dashboard, pull requests merged in 2022-02, with the labels that each got.

#12 Cost page
  src/Components/Cost.tsx
  src/Components/Dashboard.tsx
  src/Components/Items/CardComponents/Cost/TotalCostCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/IngressCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/NamespaceCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/PodCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/RepositoryCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/RessourceCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/ServiceAccountCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/StorageCardComponent.tsx
  src/Components/Items/CostTable.tsx
  src/Components/Items/Icons/CpuIcon.tsx
  src/Components/Items/Icons/NatronIcon.tsx
  src/Components/Items/Icons/NatronIconWhite.tsx
  src/Components/Items/Icons/RAMIcon.tsx
  src/Components/Login.tsx
  src/Components/Navbar.tsx
Labels: enhancement

#13 Mobile improvements
  src/App.tsx
  src/Components/Cost.tsx
  src/Components/Dashboard.tsx
  src/Components/Items/CardComponent.tsx
  src/Components/Items/FloatingTenantChange.tsx
  src/Components/Items/TenantDropdown.tsx
  src/Components/Navbar.tsx
  src/Components/Notifications.tsx
  src/Components/Settings.tsx
Labels: enhancement

#14 Drawer change
  src/App.tsx
  src/Components/Items/CardComponent.tsx
  src/Components/Items/DetailsModal.tsx
  src/Components/Items/FloatingTenantChange.tsx
  src/Components/Navbar.tsx
Labels: enhancement

#17 Mobile loginpgae fix and logout button in drawer
  src/Components/Login.tsx
  src/Components/Navbar.tsx
Labels: enhancement

#18 cleanup total cost card component
  src/Components/Items/CardComponents/Cost/TotalCostCardComponent.tsx
Labels: enhancement

#21 add logout on 403
  src/App.tsx
  src/Components/Cost.tsx
  src/Components/Items/CardComponents/Dashboard/IngressCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/NamespaceCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/PodCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/RepositoryCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/RessourceCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/ServiceAccountCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/StorageCardComponent.tsx
  src/Components/Items/TenantDropdown.tsx
  src/Components/Logout.tsx
Labels: enhancement

#22 fixed mobile login page card centering
  src/Components/Login.tsx
Labels: bug

#24 Feature branch
  src/App.tsx
  src/Assets/slack-new-logo.svg
  src/Components/Cost.tsx
  src/Components/Dashboard.tsx
  src/Components/Items/CardComponents/Dashboard/IngressCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/NamespaceCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/PodCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/RessourceCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/ServiceAccountCardComponent.tsx
  src/Components/Items/CardComponents/Dashboard/StorageCardComponent.tsx
  src/Components/Items/CardComponents/Notifications/MessageCard.tsx
  src/Components/Items/CostTable.tsx
  src/Components/Items/DonutChart.tsx
  src/Components/Items/Icons/SlackIcon.tsx
  src/Components/Navbar.tsx
  src/Components/Notifications.tsx
Labels: enhancement

#25 convert bytes to gb
  src/Components/Items/CardComponents/Dashboard/RessourceCardComponent.tsx
Labels: bug

#26 fix quota in storage
  src/Components/Items/CardComponents/Dashboard/StorageCardComponent.tsx
Labels: bug

#27 fix donut
  src/Components/Items/CardComponents/Dashboard/StorageCardComponent.tsx
Labels: bug

#30 fix storage selection
  src/Components/Items/CardComponents/Dashboard/StorageCardComponent.tsx
Labels: bug

#33 Change ingress
  src/Components/Items/CardComponents/Dashboard/IngressCardComponent.tsx
Labels: enhancement

#35 Tenant state
  src/App.tsx
  src/Components/Items/TenantDropdown.tsx
  src/Components/Notifications.tsx
Labels: bug

#36 Fix refreshpage
  src/App.tsx
  src/Components/Items/CardComponents/Dashboard/StorageCardComponent.tsx
  src/Components/Items/FloatingTenantChange.tsx
  src/Components/Items/TenantDropdown.tsx
  src/index.tsx
Labels: bug, enhancement

#37 show message when no slack messages are received
  src/Components/Notifications.tsx
Labels: bug
