Repository natron-io/tenant-dashboard, pull requests merged in 2022-01, with the labels that each got.

#1 add initial file structure
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yml
  SECURITY.md
Labels: documentation, enhancement

#5 Base UI design
  .gitignore
  package-lock.json
  package.json
  public/favicon.svg
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.tsx
  src/Assets/cpu.svg
  src/Assets/logo_big_color.svg
  src/Assets/logo_big_white.svg
  src/Assets/ram.svg
  src/Components/Content.tsx
  src/Components/Cost.tsx
  src/Components/Dashboard.tsx
  src/Components/Items/CardComponent.tsx
  src/Components/Items/CpuIcon.tsx
  src/Components/Items/DonutChart.tsx
  src/Components/Items/DrawerContext.tsx
  src/Components/Items/NatronIcon.tsx
  src/Components/Items/NatronIconWhite.tsx
  src/Components/Items/RAMIcon.tsx
  src/Components/Navbar.tsx
  src/Components/Notifications.tsx
  src/Components/Settings.tsx
  src/index.tsx
  src/react-app-env.d.ts
  tsconfig.json
Labels: enhancement

#7 change to yarn, add docker support with env variables, add basic info…
  .github/ISSUE_TEMPLATE/DOCS-REQUEST.yaml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yaml
  .github/ISSUE_TEMPLATE/FORM-BUG.yaml
  .github/ISSUE_TEMPLATE/SECURITY-BUG.yaml
  CODEOWNERS
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Dockerfile
  conf/conf.d/default.conf
  conf/conf.d/gzip.conf
  env-config.js
  env.sh
  package-lock.json
  package.json
  public/env-config.js
  tsconfig.json
  yarn.lock
Labels: enhancement

#6 Implementation of backend calls and OAuth & more
  .github/ISSUE_TEMPLATE/DOCS-REQUEST.yaml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yaml
  .github/ISSUE_TEMPLATE/FORM-BUG.yaml
  .github/ISSUE_TEMPLATE/SECURITY-BUG.yaml
  .gitignore
  CODEOWNERS
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Dockerfile
  README.md
  conf/conf.d/default.conf
  conf/conf.d/gzip.conf
  env-config.js
  env.sh
  package-lock.json
  package.json
  public/env-config.js
  src/App.tsx
  src/Assets/blob-scatter-haikei.svg
  src/Components/Content.tsx
  src/Components/Cost.tsx
  src/Components/Dashboard.tsx
  src/Components/Items/CardComponents/IngressCardComponent.tsx
  src/Components/Items/CardComponents/NamespaceCardComponent.tsx
  src/Components/Items/CardComponents/PodCardComponent.tsx
  src/Components/Items/CardComponents/RepositoryCardComponent.tsx
  src/Components/Items/CardComponents/RessourceCardComponent.tsx
  src/Components/Items/CardComponents/ServiceAccountCardComponent.tsx
  src/Components/Items/CardComponents/StorageCardComponent.tsx
  src/Components/Items/TenantDropdown.tsx
  src/Components/Login.tsx
  src/Components/Logout.tsx
  src/Components/Navbar.tsx
  src/Components/Notifications.tsx
  src/Components/Settings.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement

#9 fix env script
  .gitignore
  env-config.js
  env.sh
Labels: bug, enhancement

#10 Fix env
  README.md
  public/env-config.js
  public/index.html
  src/Components/Login.tsx
Labels: bug, documentation

#11 Add details modal to dashboard page
  .gitignore
  src/Components/Items/CardComponents/IngressCardComponent.tsx
  src/Components/Items/CardComponents/NamespaceCardComponent.tsx
  src/Components/Items/CardComponents/PodCardComponent.tsx
  src/Components/Items/CardComponents/ServiceAccountCardComponent.tsx
  src/Components/Items/DetailsModal.tsx
Labels: enhancement
